services:
  server1:
    build: .
    command: ./app
    container_name: server1
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=":8080"
    networks:
      - app-network

  server2:
    build: .
    command: ./app
    container_name: server2
    ports:
      - "8081:8081"
    environment:
      - SERVER_ADDRESS=":8081"
    networks:
      - app-network
  
  server3:
    build: .
    command: ./app
    container_name: server3
    ports:
      - "8082:8082"
    environment:
      - SERVER_ADDRESS=":8082"
    networks:
      - app-network

networks:
  app-network: